import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorkoutProvider from "@/contexts/WorkoutContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistOswald = Oswald({
  variable: "--font-geist-oswald",
  subsets: ["latin"],
});

const geistInter = Inter({
  variable: "--font-inter-custom",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistInter.variable} ${geistMono.variable} ${geistOswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-inter">
        <WorkoutProvider>
          <Navbar></Navbar>
          <main>{children}</main>
        </WorkoutProvider>
        <ToastContainer></ToastContainer>
      </body>
    </html>
  );
}
